# Generated by Django 5.2.6 on 2026-09-22 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Code')),
                ('last_name', models.CharField(max_length=120, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=120, verbose_name='Prénom')),
                ('category', models.CharField(blank=True, default='', max_length=80, verbose_name='Catégorie')),
                ('places', models.PositiveIntegerField(default=1, verbose_name='Places')),
                ('status', models.CharField(choices=[('valide', 'Valide'), ('invalide', 'Invalide'), ('desactive', 'Désactivé')], default='valide', max_length=20, verbose_name='Statut')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'import")),
                ('is_validated', models.BooleanField(db_index=True, default=False, verbose_name='Validé')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de scans')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_scanned', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('valid', 'Valide'), ('already_used', 'Déjà utilisé'), ('invalid', 'Inconnu'), ('disabled', 'Désactivé')], max_length=20)),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('agent', models.CharField(blank=True, default='', max_length=120)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='validation.invitation')),
            ],
            options={
                'verbose_name': 'Journal de scan',
                'verbose_name_plural': 'Journaux de scan',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
