# Generated by Django 5.2.6 on 2026-09-22 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_generated',
            field=models.BooleanField(default=False, verbose_name='Invitation générée'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_sent',
            field=models.BooleanField(default=False, verbose_name='Invitation envoyée'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='participant_type',
            field=models.CharField(choices=[('RECIPIENT', 'Récipiendaire'), ('VIP', 'VIP')], db_index=True, default='RECIPIENT', max_length=20, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='places_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Places utilisées'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='persons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_validated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Présent (au moins une entrée)'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='places',
            field=models.PositiveIntegerField(default=1, verbose_name='Places autorisées'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Première entrée'),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='result',
            field=models.CharField(choices=[('valid', 'Valide'), ('already_used', 'Épuisée'), ('invalid', 'Inconnu'), ('disabled', 'Désactivé'), ('recognized', 'Reconnue'), ('admitted', 'Entrée enregistrée')], max_length=20),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.PositiveIntegerField()),
                ('admitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('agent', models.CharField(blank=True, default='', max_length=120)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='validation.invitation')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'ordering': ['-admitted_at'],
            },
        ),
    ]
