# Generated by Django 5.2.17 on 2026-09-22 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_one_place_per_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLimitAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_regular', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_vip', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_total', models.PositiveIntegerField(blank=True, null=True)),
                ('new_regular', models.PositiveIntegerField(blank=True, null=True)),
                ('new_vip', models.PositiveIntegerField(blank=True, null=True)),
                ('new_total', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ajustement de limite',
                'verbose_name_plural': 'Ajustements de limites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('regular_invitation_limit', models.PositiveIntegerField(default=30, verbose_name='Limite invitations standard')),
                ('vip_invitation_limit', models.PositiveIntegerField(default=0, verbose_name='Limite invitations VIP')),
                ('total_invitation_limit', models.PositiveIntegerField(default=0, help_text='Si > 0, plafonne le total standard+VIP (ex. offre gratuite 30).', verbose_name='Limite totale (0 = non utilisée)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='Devise')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Recommandé')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formule',
                'verbose_name_plural': 'Formules',
                'ordering': ['display_order', 'price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('provider', models.CharField(default='mock', max_length=40)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=160, verbose_name='Nom affiché')),
                ('organization_name', models.CharField(blank=True, default='', max_length=160, verbose_name='Organisation')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.AlterField(
            model_name='invitation',
            name='participant_type',
            field=models.CharField(choices=[('RECIPIENT', 'Standard'), ('VIP', 'VIP')], db_index=True, default='RECIPIENT', max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('plan_update', 'Modification formule'), ('limit_adjust', 'Ajustement limite'), ('event_activate', 'Activation manuelle'), ('payment_change', 'Changement paiement'), ('event_cancel', 'Annulation'), ('other', 'Autre')], max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=60)),
                ('target_id', models.CharField(blank=True, default='', max_length=60)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité admin",
                'verbose_name_plural': "Journaux d'activité admin",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('event_type', models.CharField(choices=[('ceremony', 'Cérémonie'), ('wedding', 'Mariage'), ('graduation', 'Remise de diplômes'), ('conference', 'Conférence'), ('gala', 'Gala'), ('birthday', 'Anniversaire'), ('reception', 'Réception'), ('professional', 'Événement professionnel'), ('other', 'Autre')], default='other', max_length=40, verbose_name='Type')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('venue', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Ville')),
                ('organizer_name', models.CharField(blank=True, default='', max_length=160, verbose_name='Organisateur')),
                ('contact_information', models.CharField(blank=True, default='', max_length=255, verbose_name='Contact')),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='flyers/%Y/%m/', verbose_name='Flyer')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/', verbose_name='Logo')),
                ('primary_color', models.CharField(blank=True, default='#F26522', max_length=16, verbose_name='Couleur principale')),
                ('welcome_text', models.TextField(blank=True, default='', verbose_name="Texte d'accueil")),
                ('invitation_message', models.TextField(blank=True, default='', verbose_name="Message d'invitation")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_payment', 'En attente de paiement'), ('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=32, verbose_name='Statut')),
                ('code_prefix', models.CharField(help_text="Préfixe des codes d'invitation (ex. ATC24, EVT7K2).", max_length=24, unique=True, verbose_name='Préfixe QR')),
                ('plan_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('regular_limit_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('vip_limit_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('total_limit_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency_snapshot', models.CharField(blank=True, default='', max_length=8)),
                ('custom_regular_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_vip_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_total_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_legacy', models.BooleanField(default=False, help_text='Conserve la compatibilité ATC24 / VIP existants.', verbose_name='Événement historique migré')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='validation.event'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='validation.event'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='validation.event'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['event', 'participant_type'], name='validation__event_i_8aac74_idx'),
        ),
        migrations.AddField(
            model_name='eventlimitadjustment',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_limit_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventlimitadjustment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_adjustments', to='validation.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='validation.eventplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='validation.event'),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='validation.eventplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'status'], name='validation__owner_i_d3beac_idx'),
        ),
    ]
