# Generated by Django 5.2.17 on 2026-09-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0006_seed_plans_and_legacy_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text="Si activé et qu'un flyer est présent, l'événement apparaît dans le carrousel public.", verbose_name="Afficher sur la page d'accueil"),
        ),
    ]
