# Generated by Django 5.2.17 on 2026-09-22 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0007_event_show_on_homepage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='unique_profile_phone_nonempty'),
        ),
    ]
