# Generated by Django 5.2.17 on 2026-09-24 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0012_recommend_moyen_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivé le'),
        ),
        migrations.AddField(
            model_name='event',
            name='delete_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proposition de suppression refusée le'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending_payment', 'En attente de paiement'), ('active', 'Actif'), ('completed', 'Terminé'), ('archived', 'Archivé'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=32, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'date'], name='validation__status_2f70b6_idx'),
        ),
    ]
