# Generated by Django 5.2.17 on 2026-09-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0023_site_email_seo_mock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('plan_update', 'Modification formule'), ('limit_adjust', 'Ajustement limite'), ('event_activate', 'Activation manuelle'), ('payment_change', 'Changement paiement'), ('payout', 'Reversement Mobile Money'), ('event_cancel', 'Annulation'), ('other', 'Autre')], max_length=40),
        ),
    ]
