# Generated by Django 5.2.17 on 2026-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0029_ticketing_controllers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('valide', 'Valide'), ('invalide', 'Invalide'), ('desactive', 'Annulée')], default='valide', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Type'),
        ),
    ]
