# Generated by Django 5.2.17 on 2026-09-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0030_invitation_status_tickettier_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auth_login_image',
            field=models.ImageField(blank=True, help_text='Fond des écrans login / inscription / mot de passe. Vide = image hero, sinon galerie.', null=True, upload_to='site/', verbose_name='Image pages de connexion'),
        ),
    ]
